### ISSUE TITLE
Add the ability to add renaming to favorites

### ISSUE THREAD

**Issue by TRemill** [HiWord9/RPRenames-fabric#13]
It would be nice to see the possibility of adding favorite renames to favorites.

For example, with a clamped shift, mark favorite renaming. And activate this mode by clicking on the button in the upper right corner. And then it's inconvenient to scroll through 50 pages in order to make a couple of renames in large numbers.

![image](https://user-images.githubusercontent.com/69728227/234066194-ed9cc225-5b27-4a5c-bd6f-8ea361d9863a.png)

**Comment by HiWord9** [comment]
I shouldve been made this feature early, but i wasn't able to code because of some irl issues. I got this idea for like a week ago, and i started doing it only a few days ago, and it is almost ready for upload in new version, here are some spoilers
![image](https://user-images.githubusercontent.com/46609661/234119220-91452d99-255f-4858-8c8a-6da206d69e90.png)
![image](https://user-images.githubusercontent.com/46609661/234119317-35783f43-defe-4f80-acc4-f60710c27b16.png)
