### ISSUE TITLE
Russian word fix

### ISSUE THREAD

**Issue by Snrrr** [HiWord9/RPRenames-fabric#29]
Not showing textures in russian language, but if write it its showing the texture.
![image](https://github.com/HiWord9/RPRenames-fabric/assets/95704921/a81414ad-8729-4e77-92e5-d0b4d2bcc876)

**Comment by HiWord9** [comment]
have u tryed to update ur packs with f3+t?

**Comment by Kofiy** [comment]
Additional info:

- It doesn't only display unknown/broken encoding symbols as `?`, but it actually turns them into question mark symbol
  - That's actually the reason why it doesn't display texture/model. When you click on button it will put "?????" into name field (instead of `Кинжал` or `\u041a\u0438\u043d\u0436\u0430\u043b` (utf-16 encoding)).

**Comment by HiWord9** [comment]
Provide a game log please

**Comment by HiWord9** [comment]
fixed in 0.7.0
