### ISSUE TITLE
incompatibility with bclib

### ISSUE THREAD

**Issue by MoisesVQ** [HiWord9/RPRenames-fabric#40]
I can see the animation when i put the cursor on top of the button, but nothing happens when i click it.

**Comment by HiWord9** [comment]
Please provide more info as version of mod and minecraft where it happens and list of resource packs u use

**Comment by maiguel5** [comment]
Hi! same problem here, over 300 mods in use.
Fabric 1.19.2
v0.7.0 of the mod
Resume: i can see first page but button to the next page is doing nothing :) happens in every anvil
RP in use: "Grimdark-Armor-v2-5-09" and "BarelyDefault_V10"

Update 1: It seems to happen when bclib is installed, will test further to search other mods in conflict :) (It is sad since you need bclib to some good mods like better nether and better end)

**Comment by maiguel5** [comment]
[latest.log](https://github.com/HiWord9/RPRenames-fabric/files/13970013/latest.log)
Here you have a log with minimun mods installed, i hope it helps ^^
Tried the same with bclib 2.1.2 and 2.1.8

Greetings and good luck! i will stay on focus if you solve :D

**Comment by HiWord9** [comment]
> [latest.log](https://github.com/HiWord9/RPRenames-fabric/files/13970013/latest.log) Here you have a log with minimun mods installed, i hope it helps ^^ Tried the same with bclib 2.1.2 and 2.1.8
> 
> Greetings and good luck! i will stay on focus if you solve :D

Thank you a lot for giving me all this valuable information! Now i am sure what's going on, there is incompatibility with bclib.
Actually, i was going to close this issue as not planned cause i thought there was just 20 renames multiple time [but for different items](https://github.com/HiWord9/RPRenames-fabric/issues/42), and visually nothing changed. Now i know how to work with it

**Comment by HiWord9** [comment]
fixed in 0.8.0
