### ISSUE TITLE
Book Button Retexture Request

### ISSUE THREAD

**Issue by GrandPappyJay** [HiWord9/RPRenames-fabric#5]
This issue is a request.

The textures I am using are edits from Excalibur (credit to Maffhew)

I would like to have the book button work as follows
     No CIT available ( current bottom texture )
     ![image](https://user-images.githubusercontent.com/55817923/231304091-abad0d5d-d7cf-4ee6-9d48-3278c9d867be.png)
     CIT available ( top texture )
     ![image](https://user-images.githubusercontent.com/55817923/231304285-3f301be5-27ad-41c1-8f10-010c3859ede0.png)
     Window Selection Screen open ( new texture )
     ![image](https://user-images.githubusercontent.com/55817923/231304522-15c3db07-4f63-4ec5-80a1-e05f21ff023b.png)
     Button highlighted ( middle texture )
     ![image](https://user-images.githubusercontent.com/55817923/231305194-705f698a-de9c-49a7-8a60-8d0b05dc4057.png)

**Comment by HiWord9** [comment]
I was thinking about creating a few extra resource packs for this menu, like blue variant or vanilla-like and post them as downloadable content. Because it is really easy to make custom textures for this mod and that would be a good example. Your request made me thinking about adding them right into the mod for everyone be able to change this "default skins".
Your textures looks pretty good, i like it, i think, that i would do something with them if i decide to add rps.
The texture for opened is posiible and also i would do that, but there is a bug in minecraft that i can't fix and that is quite bad thing. When u clicking on a button and then click on other one, the first one changes texture to hovered variant, even without u targeting it. U can produce it by ursefl, just click any rename button twice and u'ill see that this gets white frame. But, luckly, this is not a problem that would prevent me from adding this and i think it wont be an issue, telling the bug just for knowing.
Thanks for ur attention and time spended for this

**Comment by HiWord9** [comment]
Please send there this textures 18x18. I'm about to add a few custom rps and one of them will be excalibur-like variant

**Comment by GrandPappyJay** [comment]
Nice! I will touch up the textures and send this evening...

**Comment by GrandPappyJay** [comment]
Here are the textures I have created as Excalibur support...  I did get Maffhew's permission to share these with you since they are based on his work...  If you include credit for textures anywhere please list both Maffhew and GrandPappyJay (myself)... Thanks!

![available](https://user-images.githubusercontent.com/55817923/231604331-aef9e1ab-c708-4149-ac85-0a8339c02484.png)
![highlighted](https://user-images.githubusercontent.com/55817923/231604332-594b92ba-5b78-4188-ad64-2a669b61932d.png)
![not_available](https://user-images.githubusercontent.com/55817923/231604334-3179bc87-2d86-4e82-bac8-ede797c2da48.png)
![open](https://user-images.githubusercontent.com/55817923/231604335-0de23b02-3826-4049-b588-04c4a3eace87.png)
![renames_menu](https://user-images.githubusercontent.com/55817923/231604339-a9575c77-af3b-4cb4-b53c-816326c2520f.png)

**Comment by HiWord9** [comment]
![rename_menu](https://user-images.githubusercontent.com/46609661/231610847-530b22b2-2017-44ad-8dd7-594db1eed5e3.png)
I did this texture by myself based on those pics uve send before. I think this variant better because buttons are not overhighlighted, as on urs.
I am making this rp as an example and i am not going to add it right into the mod, only as downloadable somewhere on this mod's git page.
Btw now i am experementing with adding extra texture, the one for opened variant and, as u can see on texture, i have first and i guess last prototipe of Maffhew's Excalibur style rp

**Comment by GrandPappyJay** [comment]
What I provided was made using assets and edits straight from Maffhew's pack... The brighter styled buttons are what he uses in he pack already...

**Comment by HiWord9** [comment]
![image](https://user-images.githubusercontent.com/46609661/231614490-ce9c6bf3-b5ef-4e7f-9609-7450f29dc8cf.png)
That's how it looks like in game. Ive finished extra texture system.
[RPR Excalibur style.zip](https://github.com/HiWord9/RPRenames-fabric/files/11217068/RPR.Excalibur.style.zip)
This is the version ive made. What u think? Do u agree with this final  version as author?

**Comment by GrandPappyJay** [comment]
It looks close, certainly Excalibur inspired... Thank you very much for the button change!

**Comment by HiWord9** [comment]
I havent use the excalibur and i wasnt know about its style enough. U know, if the pack for Excalibur users, it should be the same. So i am going to make buttons as u said he already did

**Comment by HiWord9** [comment]
> It looks close, certainly Excalibur inspired... Thank you very much for the button change!

Thanks for an idea!

**Comment by HiWord9** [comment]
Added opened variant of button to 0.1.1, also added two build-in resource packs as i told im going. Ur rp for Excalibur now can be found on wiki on page with guide about creating ur own rp for mod's gui
https://github.com/HiWord9/RPRenames-fabric/wiki/Creating-custom-textures-for-mod's-menu
