### ISSUE TITLE
1.21 support?

### ISSUE THREAD

**Issue by rorosin** [HiWord9/RPRenames-fabric#57]
Is 1.21 support planned?

**Comment by AriqMicin** [comment]
yeah, i really need it for my texture pack

**Comment by HiWord9** [comment]
I would love to, but sadly the whole cit system which rprenames is based on still didn't got updated to 1.20.5 and newer. The problem is new components introduced in 1.20.5 that are replacing old regular nbt tags, it's seems to be difficult to rebase all cits to components. The discussion about properties format is goes [here](https://github.com/sp614x/optifine/issues/7658). I'm personally waiting for this thread to be logically finished and for cit resewn to get updated too.

**Comment by HiWord9** [comment]
https://github.com/SHsuperCM/CITResewn/issues/446
omg
Looks like soon i'll start porting rpr to 1.21

**Comment by dexter-dex131** [comment]
Cant Wait for the 1.21 port :D

**Comment by HiWord9** [comment]
> Cant Wait for the 1.21 port :D

me too honestly

**Comment by Fireflasher21** [comment]
CIT Resewn just uploaded a beta this week for the [1.21](https://modrinth.com/mod/cit-resewn/version/1.2.0+1.21) Version.
I hope that version works for you

**Comment by Mozuzu222** [comment]
Hope it comes soon..

**Comment by sh2kcs** [comment]
pls...

**Comment by dexter-dex131** [comment]
when is the release :<

**Comment by AriqMicin** [comment]
nice

**Comment by HiWord9** [comment]
> when is the release :<

i will make a thing that if mod detects ur specific nickname it will crash the game on purpose >:)

**Comment by HiWord9** [comment]
First alpha port for 1.21.x (0.9.1.1) is now available https://modrinth.com/mod/rp-renames
